# Generated by Django 3.2.15 on 2023-01-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Double',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=40)),
                ('scanner', models.CharField(choices=[('angel', 'angel'), ('latif', 'latif'), ('windi', 'windi'), ('antarestar', 'antarestar')], max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.CharField(max_length=40)),
                ('scanner', models.CharField(choices=[('angel', 'angel'), ('latif', 'latif'), ('windi', 'windi'), ('antarestar', 'antarestar')], max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sortir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=40)),
                ('scanner', models.CharField(choices=[('angel', 'angel'), ('latif', 'latif'), ('windi', 'windi'), ('antarestar', 'antarestar')], max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
